#pragma once

/**
 * model_writer — serialize a BoxModel back to a Python `model = {…}` file.
 *
 * Companion to model_loader.h. The output round-trips through the loader's
 * tokenizer-only parser (so: `import math`, plain float/int literals, no
 * variable references, `True`/`False`/`None` allowed). Used by the in-game
 * model editor to persist edits to artifacts/models/{base,player}/*.py.
 *
 * What we emit:
 *   - top-level scalars: id, height, scale, walk_speed, idle_bob, walk_bob
 *   - hand attachment points: hand_r/l, pivot_r/l (omitted if defaulted)
 *   - parts list: name?, role?, head?, offset, size, color, pivot?,
 *                  swing_axis?, amplitude?, phase?, speed?
 *   - clips dict: { name → { partName → {axis, amp, bias, phase, speed} } }
 *
 * What we don't preserve:
 *   - comments and original formatting (this is a regenerator)
 *   - `equip` field — currently lives only on item models, not character models
 *
 * Format invariants chosen to keep diffs against hand-written .py readable:
 *   - integer-valued floats emit as ints ("0" not "0.0")
 *   - math.pi multiples (±0.5, ±1, ±2) emit symbolically
 *   - parts emit one-per-line for diffability
 */

#include "client/box_model.h"
#include <cmath>
#include <sstream>
#include <string>

namespace civcraft::model_writer {

inline std::string fmtNum(float v) {
	// Recognize math.pi multiples so swing phases stay readable.
	const float pi = 3.14159265358979323846f;
	const float mults[] = {1.0f, -1.0f, 0.5f, -0.5f, 2.0f, -2.0f};
	for (float m : mults) {
		if (std::fabs(v - pi * m) < 1e-5f) {
			char buf[32];
			if (m == 1.0f) return "math.pi";
			if (m == -1.0f) return "-math.pi";
			if (m > 0) snprintf(buf, sizeof(buf), "math.pi * %g", m);
			else snprintf(buf, sizeof(buf), "-math.pi * %g", -m);
			return buf;
		}
	}
	char buf[32];
	if (v == (int)v && std::fabs(v) < 1e9f) {
		snprintf(buf, sizeof(buf), "%d", (int)v);
	} else {
		snprintf(buf, sizeof(buf), "%g", v);
	}
	return buf;
}

inline std::string fmtVec3(const glm::vec3& v) {
	return "[" + fmtNum(v.x) + ", " + fmtNum(v.y) + ", " + fmtNum(v.z) + "]";
}
inline std::string fmtVec4(const glm::vec4& v) {
	return "[" + fmtNum(v.x) + ", " + fmtNum(v.y) + ", " +
	       fmtNum(v.z) + ", " + fmtNum(v.w) + "]";
}

inline bool nearly(const glm::vec3& a, const glm::vec3& b, float eps = 1e-5f) {
	return std::fabs(a.x - b.x) < eps && std::fabs(a.y - b.y) < eps &&
	       std::fabs(a.z - b.z) < eps;
}

inline std::string emitPart(const BodyPart& p) {
	std::ostringstream out;
	out << "{";
	bool first = true;
	auto kv = [&](const std::string& k, const std::string& v) {
		if (!first) out << ", ";
		out << "\"" << k << "\": " << v;
		first = false;
	};
	if (!p.name.empty()) kv("name", "\"" + p.name + "\"");
	if (p.isHead) kv("head", "True");
	if (!p.role.empty()) kv("role", "\"" + p.role + "\"");
	kv("offset", fmtVec3(p.offset));
	// Loader stores halfSize but the .py format uses full size.
	glm::vec3 fullSize = p.halfSize * 2.0f;
	kv("size", fmtVec3(fullSize));
	kv("color", fmtVec4(p.color));
	// Pivot is always emitted — loader defaults absent pivot to (0,0,0),
	// which is semantically distinct from pivot=offset.
	kv("pivot", fmtVec3(p.pivot));
	if (p.swingAmplitude != 0.0f) {
		// Match the loader's key names from artifacts/models/*.py.
		if (!nearly(p.swingAxis, glm::vec3(1, 0, 0)))
			kv("swing_axis", fmtVec3(p.swingAxis));
		kv("amplitude", fmtNum(p.swingAmplitude));
		if (p.swingPhase != 0.0f) kv("phase", fmtNum(p.swingPhase));
		if (p.swingSpeed != 1.0f) kv("speed", fmtNum(p.swingSpeed));
	}
	out << "}";
	return out.str();
}

inline std::string emitModelPy(const BoxModel& m, const std::string& id) {
	std::ostringstream out;
	out << "\"\"\"Auto-generated by the in-game model editor.\n\n"
	       "Edit via Handbook → select model → Edit. Saving regenerates\n"
	       "this file; comments and formatting are not preserved.\n"
	       "\"\"\"\n\n"
	       "import math\n\n"
	       "model = {\n";
	out << "    \"id\": \"" << id << "\",\n";
	out << "    \"height\": " << fmtNum(m.totalHeight) << ",\n";
	out << "    \"scale\": " << fmtNum(m.modelScale) << ",\n";
	out << "    \"walk_speed\": " << fmtNum(m.walkCycleSpeed) << ",\n";
	out << "    \"idle_bob\": " << fmtNum(m.idleBobAmount) << ",\n";
	out << "    \"walk_bob\": " << fmtNum(m.walkBobAmount) << ",\n";
	// Hand attach points — only emit if non-default (heuristic: if any
	// component is non-zero and the model defines a head, it's a character).
	auto vecNonZero = [](const glm::vec3& v) {
		return v.x != 0 || v.y != 0 || v.z != 0;
	};
	if (vecNonZero(m.handR))  out << "    \"hand_r\": "  << fmtVec3(m.handR)  << ",\n";
	if (vecNonZero(m.handL))  out << "    \"hand_l\": "  << fmtVec3(m.handL)  << ",\n";
	if (vecNonZero(m.pivotR)) out << "    \"pivot_r\": " << fmtVec3(m.pivotR) << ",\n";
	if (vecNonZero(m.pivotL)) out << "    \"pivot_l\": " << fmtVec3(m.pivotL) << ",\n";
	if (vecNonZero(m.headPivot))
		out << "    \"head_pivot\": " << fmtVec3(m.headPivot) << ",\n";

	out << "    \"parts\": [\n";
	for (auto& p : m.parts) out << "        " << emitPart(p) << ",\n";
	out << "    ],\n";

	if (!m.clips.empty()) {
		out << "    \"clips\": {\n";
		for (auto& [clipName, clip] : m.clips) {
			out << "        \"" << clipName << "\": {\n";
			for (auto& [partName, ov] : clip.overrides) {
				out << "            \"" << partName << "\": {";
				out << "\"axis\": " << fmtVec3(ov.axis);
				out << ", \"amp\": " << fmtNum(ov.amplitude);
				if (ov.bias != 0)  out << ", \"bias\": "  << fmtNum(ov.bias);
				if (ov.phase != 0) out << ", \"phase\": " << fmtNum(ov.phase);
				if (ov.speed != 1) out << ", \"speed\": " << fmtNum(ov.speed);
				out << "},\n";
			}
			out << "        },\n";
		}
		out << "    },\n";
	}

	out << "}\n";
	return out.str();
}

} // namespace civcraft::model_writer
