// CreatureForge — Morphology Graph
//
// The single source of truth for a creature. Everything downstream
// (mesh, skeleton, physics asset, material, behavior) is *derived*
// from this struct tree. Save files are this struct, serialized.
//
// Design goals:
//   - Small on disk (<10 KB typical) — one array of part instances,
//     one spine, one paint stack, one behavior graph.
//   - Diff-able — parts keyed by stable GUID so two branches of the
//     same creature can be merged without renumbering.
//   - Forward-compatible — SchemaVersion + per-struct reserved floats;
//     loaders clamp unknown fields, never crash.
//   - Cheap to hash — incremental recompilation keys off per-subgraph
//     hashes (FSpine, FPartInstance, FPaintStack, FBehaviorGraph).
//
// This file is data only. No UObjects, no BlueprintCallable methods;
// the compiler (Source/Private/BodyCompiler.cpp) consumes this.

#pragma once

#include "CoreMinimal.h"
#include "MorphologyGraph.generated.h"

// --------------------------------------------------------------------
// Versioning
// --------------------------------------------------------------------
// Bump MajorVersion on breaking changes only. Add-only field changes
// bump MinorVersion. The loader refuses Major mismatches and warns on
// Minor mismatches.
namespace CreatureForge::Schema {
	constexpr int32 MajorVersion = 1;
	constexpr int32 MinorVersion = 0;
}

// --------------------------------------------------------------------
// Spine — a polyline with thickness. The implicit body surface is
// generated by sweeping a capsule field along this curve, unioned
// with all soft parts.
//
// Control points are in creature-local space, meters. Index 0 is the
// root (hip / pelvis); last index is the head tip. Minimum 2 points;
// typical 4–8.
// --------------------------------------------------------------------
USTRUCT(BlueprintType)
struct FSpineNode
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere) FVector Position = FVector::ZeroVector;

	// Body thickness at this node, in meters. Clamped to [0.02, 2.0]
	// in the compiler — zero-thickness segments break meshing.
	UPROPERTY(EditAnywhere) float Thickness = 0.25f;

	// Twist about the local forward axis, radians. Lets the user give
	// the body a helical skew without moving control points.
	UPROPERTY(EditAnywhere) float TwistRadians = 0.0f;
};

USTRUCT(BlueprintType)
struct FSpine
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere) TArray<FSpineNode> Nodes;

	// Catmull-Rom tension. 0 = straight segments, 1 = fully rounded.
	UPROPERTY(EditAnywhere, meta=(ClampMin="0.0", ClampMax="1.0"))
	float Tension = 0.5f;
};

// --------------------------------------------------------------------
// Part instance — one palette part dropped onto the body.
//
// Attach model: (SplineT, AngleAroundSpine) is a cylindrical coordinate
// on the spine. The compiler raymarches from (spine sample at SplineT)
// outward along (body-local frame rotated by AngleAroundSpine) until
// it hits the implicit surface, and places the part there with its
// up-axis along the surface normal. This keeps attachments stable
// across body edits — a leg stays on the hip even if the user
// thickens the torso.
//
// Asymmetry: when > 0, the compiler *also* spawns a mirrored clone
// across the XZ (sagittal) plane, with placement interpolated between
// mirror (Asymmetry=0) and free (Asymmetry=1). Exact mirror is the
// common case; partial asymmetry produces believably-organic cheats.
// --------------------------------------------------------------------
USTRUCT(BlueprintType)
struct FPartDeform
{
	GENERATED_BODY()

	// All deforms are per-instance, per-part. Clamped server-side
	// (at compile time) to ranges declared on the UCreaturePartAsset.

	UPROPERTY(EditAnywhere) float Scale       = 1.0f;  // uniform scale
	UPROPERTY(EditAnywhere) float Taper       = 0.0f;  // tip thinning, [-1,1]
	UPROPERTY(EditAnywhere) float Bend        = 0.0f;  // tip bend arc, [-1,1]
	UPROPERTY(EditAnywhere) float Twist       = 0.0f;  // axial twist, [-1,1]
	UPROPERTY(EditAnywhere) float Thickness   = 0.0f;  // radial fatten, [-1,1]
};

USTRUCT(BlueprintType)
struct FPartInstance
{
	GENERATED_BODY()

	// Stable identity. Survives reordering, merge-compatible.
	UPROPERTY(EditAnywhere) FGuid InstanceId;

	// Soft reference so part assets can be hot-reloaded/removed
	// without corrupting the save. Missing parts become red "??"
	// placeholders in the editor rather than crashing.
	UPROPERTY(EditAnywhere) TSoftObjectPtr<class UCreaturePartAsset> Part;

	// Attach coordinate on the spine. SplineT in [0,1] along arclength.
	UPROPERTY(EditAnywhere, meta=(ClampMin="0.0", ClampMax="1.0"))
	float SplineT = 0.5f;

	// Radians around the spine local frame. 0 = dorsal (up), pi/2 = right.
	UPROPERTY(EditAnywhere) float AngleAroundSpine = 0.0f;

	// Extra orientation, applied after surface-normal alignment.
	UPROPERTY(EditAnywhere) FRotator LocalRotation = FRotator::ZeroRotator;

	UPROPERTY(EditAnywhere) FPartDeform Deform;

	// Mirror/asymmetry. 0 = exact mirror, 1 = no mirror twin spawned.
	// Values in between place the twin at a lerped position — the
	// "walking sidewise fish" look.
	UPROPERTY(EditAnywhere, meta=(ClampMin="0.0", ClampMax="1.0"))
	float Asymmetry = 0.0f;
};

// --------------------------------------------------------------------
// Paint stack — composable material layers in creature-UV space.
//
// Evaluated in array order; later layers composite over earlier ones
// using PerLayerBlendMode. Patterns are *procedural* so they survive
// arbitrary body deformation without UV seams.
//
// Soft pointer to layer asset for hot-reload; mask is a render-target
// painted in-editor (stored elsewhere, referenced by GUID).
// --------------------------------------------------------------------
UENUM(BlueprintType)
enum class EPaintBlendMode : uint8
{
	Normal, Multiply, Screen, Overlay, Add
};

USTRUCT(BlueprintType)
struct FPaintLayer
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere) FGuid LayerId;
	UPROPERTY(EditAnywhere) TSoftObjectPtr<class UPaintLayerAsset> Layer;
	UPROPERTY(EditAnywhere) FLinearColor Tint = FLinearColor::White;
	UPROPERTY(EditAnywhere, meta=(ClampMin="0.0", ClampMax="1.0"))
	float Opacity = 1.0f;
	UPROPERTY(EditAnywhere) EPaintBlendMode BlendMode = EPaintBlendMode::Normal;

	// GUID of the render-target mask painted by the user. Empty = full.
	// Mask texture assets live under /Game/Creatures/{CreatureId}/Masks/.
	UPROPERTY(EditAnywhere) FGuid MaskId;
};

USTRUCT(BlueprintType)
struct FPaintStack
{
	GENERATED_BODY()
	UPROPERTY(EditAnywhere) TArray<FPaintLayer> Layers;
};

// --------------------------------------------------------------------
// Behavior graph — trivial node model, kept tiny.
//
// Compiled to a runtime StateTree at ecosystem-drop time. The editor
// is a visual node graph; we store only the graph, not the compiled
// runtime form.
// --------------------------------------------------------------------
UENUM(BlueprintType)
enum class EBehaviorNodeKind : uint8
{
	// Sensors
	SeePrey, SeePredator, HearSound, SmellFood,
	// States
	Idle, Wander, Chase, Flee, Forage, Display,
	// Actions (leaves)
	MoveTo, Bite, Flap, Sing,
};

USTRUCT(BlueprintType)
struct FBehaviorNode
{
	GENERATED_BODY()
	UPROPERTY(EditAnywhere) FGuid NodeId;
	UPROPERTY(EditAnywhere) EBehaviorNodeKind Kind = EBehaviorNodeKind::Idle;
	// Up to 3 outgoing edges by target NodeId. Keeps layout simple.
	UPROPERTY(EditAnywhere) TArray<FGuid> Next;
	// Free-form parameters; interpretation depends on Kind.
	UPROPERTY(EditAnywhere) TArray<float> Params;
};

USTRUCT(BlueprintType)
struct FBehaviorGraph
{
	GENERATED_BODY()
	UPROPERTY(EditAnywhere) TArray<FBehaviorNode> Nodes;
	UPROPERTY(EditAnywhere) FGuid RootNodeId;
};

// --------------------------------------------------------------------
// Top-level save record
// --------------------------------------------------------------------
USTRUCT(BlueprintType)
struct FMorphologyGraph
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere) int32 SchemaMajor = CreatureForge::Schema::MajorVersion;
	UPROPERTY(EditAnywhere) int32 SchemaMinor = CreatureForge::Schema::MinorVersion;

	UPROPERTY(EditAnywhere) FGuid CreatureId;
	UPROPERTY(EditAnywhere) FString DisplayName;

	UPROPERTY(EditAnywhere) FSpine Spine;
	UPROPERTY(EditAnywhere) TArray<FPartInstance> Parts;
	UPROPERTY(EditAnywhere) FPaintStack Paint;
	UPROPERTY(EditAnywhere) FBehaviorGraph Behavior;

	// DNA budget currently spent. Recomputed from Parts on every compile;
	// persisted only so external tools can read it without a compiler.
	UPROPERTY(VisibleAnywhere) int32 DnaCostCached = 0;

	// --- Hashing (for incremental recompile) ------------------------
	// Each subgraph hashes its own fields; the compiler stores the
	// last-seen hashes and only rebuilds the affected passes.
	uint32 HashSpine()    const;
	uint32 HashParts()    const;
	uint32 HashPaint()    const;
	uint32 HashBehavior() const;
};
